#!/bin/bash

#Checking to see if the Zend Framework 2 already exists. If it does then won't install it again.
grep -q phpinfo index.php
if [ ! -e "/var/www/html/index.php" ] || grep -q phpinfo index.php; then 
	echo "Zend Framework 2 doesn't appear to be installed, installing now ..."
	rm -rf /var/www/html/*
	rmdir /var/www/html
	cd /var/www
	composer create-project -sdev --repository-url="https://packages.zendframework.com" zendframework/skeleton-application .
	mv public html
else
	echo "Zend Framework 2 appears to already be installed, no action taken."
	exit 0
fi

# chmod 755 /var/www
